naive search/naive.java
=> naive search in java

longest increasing subsequence/Lis.java
=> added LIS in Java

queue/Queue.py
=> add queue implementation

bubble sort/bubble sort.c, merge sort/mergesort.py
=> add bubble sort in c

selection sort/selection sort.py
=> selection sort algo

linked list/README.md, linked list/linked list.py
=> linked list in python

merge sort/MergeSort.java
=> merge sort using java

bubble_sort/bubble_sort.c
=> Bubble sort resolved

queue/Queue.c
=> implementation queue

binary_search/Binary_search.py
=> {binary search}{ modify and improve code}- {TrojanX}

longest common subsequence/LongestCommonSubsequence.java
=> created longest common subsequence in java

insertion_sort/InsertionSort.java, selection_sort/SelectionSort.java
=> {Insertion Sort}{Modify a loop  and remove unused code}-{TrojanX}

binary_search_tree/binary_search_tree.py, queue/Queue.py, stack/stack.py
=> {Queue}{improve code and create commandline interface}-{TrojanX}

binary_search_tree/Binarysearch.c
=> Implement binary search in C

binary_search_tree/BFS.c, binary_search_tree/Binarysearch.c
=> Implement BFS in c {Team src}

binary_search_tree/BFS.c, binary_search_tree/Binarysearch.c, binary_search_tree/primefactor.c
=> Implement prime factor in c

bubble_sort/bubble_sort.c
Update the program to any number of inputs and, display both ascending and descending order.
=> Team Code Builders-Updated to any number of inputs

Shellsort.c, binary_search_tree/BFS.c, binary_search_tree/Binarysearch.c, binary_search_tree/primefactor.c
=> Shellsort branch {Team src}

Heapsort.c, Knn.c, Shellsort.c, binary_search_tree/BFS.c, binary_search_tree/Binarysearch.c, binary_search_tree/primefactor.c
=> Implement Knn sort in c {Team src}

Heapsort.c, Shellsort.c, binary_search_tree/BFS.c, binary_search_tree/Binarysearch.c, binary_search_tree/primefactor.c
=> Heapsort {Team src}

doubly_linked_list/doubly_linked_list.py, linked_list/linked_list.py, queue/Queue.c, selection_sort/selection_sort.py
=> Dev d link list

binary_search_tree/BST.java, selection_sort/SelectionSort in c
=> Selection sort

selection_sort/selection_sort, stack/Stack linked list
=> Team Code Builders-Stack Implementation in c

queue/queue in c
=> Team Code Builders-Queue Implementation in c

binary_search/Binary_Search, binary_search/Binary_Search[C++], binary_search_tree/Binary Search Tree
=> Team Code Builders-Binary Search Tree Implementation in c

binary_search_tree/BST.java, merge_sort/Merge Sort in C
=> Merge sort in c

doubly_linked_list/doubleLimkedList.c
=> Team Code Builders - Double Linked List

insertion_sort/insertionSort.c, queue/newqueue.c
=> Queue algorithm{X-Team}

doubly_linked_list/Doubly_linked_list in C, stack/Stack linked list
=> Doubly linked list

queue/Demo.java
=> Team-X001, Queue Implementation done in java(Dynamically)

linked_list/README.md, linked_list/linked_list_queue.c
=> SAG4X-Linked list queue in [C]

linked_list/linked_list.py, naive_search/Naive_search.cpp, queue/Queue.c, selection_sort/selection_sort.py
=> Dev naive search

linked_list/Dev linked_list.py, linked_list/linked_list.py, queue/Queue.c, selection_sort/selection_sort.py
=> Dev linked list

linked_list/linked_list.py, naive_search/naive.java, queue/Queue.c, selection_sort/selection_sort.py
=> Dev naive search java

binary_search/Binary_search.py, linked_list/linked_list.py, queue/Queue.c, selection_sort/selection_sort.py
=> Dev binary search py

.vscode/c_cpp_properties.json, binary_search/BinarySearch.c, linked_list/Linked list.c, stack/Stack.c
=> stack in c

KMP String Matching/KMPStringMatching.java, linked_list/linked_list.py, queue/Queue.c, selection_sort/selection_sort.py
=> Dev kmp string match

naive_search/naive.js
Implemented the naive search in java script language
=> Naive search JS

insertion_sort/insertionSort.py
=> Added insertion sort in Python

algorithms/ar-bsrh/.gitignore, algorithms/ar-bsrh/typescript/binary_search.ts
**Fixes #367 **
-   [x] This pull request shall only be merged once the build passes. (You can merge if everything fine)
- …
=> binary_search for typescript implemented

README.md, algorithms/ar-isrt/c/insertion_sort.c
**Fixes [#387](https://github.com/FOSS-UCSC/FOSSALGO/issues/387)** …
=> Added Insertion Sort in C

algorithms/ar-bsrt/python3/bubble_sort_exe.py
**Hi!**  
---
**Fixes #404**
-   [x] This pull request has a descriptive title. …
=> Added python program for bubble sort

README.md, algorithms/ar-binsrt/python3/binsrt.py
**Hi!**  
---
**Fixes #433 **
-   [&#10004; ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [&#10004; ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [&#10004; ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [&#10004; ] This pull …
=> Bin-Sort in Python

README.md, algorithms/gr-bfsrh/python3/breadth_first_search.py
**Hi!**  
---
**Fixes #459 **
-   [x] This pull request has a descriptive title. …
=> added breadth first search in python3

algorithms/ar-binsrt/README.md
**Hi!**  
---
**Fixes #442 
For …
=> Added simple documentation for bin sort algorithm

README.md, algorithms/gr-bfsrh/csharp/BreadthFirst.cs
**Hi!**  
---
**Fixes #457 **
-   [&#10004; ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [&#10004; ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [&#10004; ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [&#10004; ] This pull …
=> Breadth First Search in C# and update readme file

algorithms/ar-binsrt/README.md, algorithms/ar-isrt/golang/insertion_sort.go
**Hi!**  
---
**Fixes #465 
For …
=> Added insertion sort in Go

README.md, algorithms/ar-binsrt/cpp/binsrt.cpp
**Hi!**  
---
**Fixes #431 **
-   [&#10004; ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [&#10004; ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [&#10004; ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [&#10004; ] This pull …
=> Bin-Sort in C++ and update readme

README.md, algorithms/ar-binsrt/c/binsrt.c
**Hi!**  
---
**Fixes #430 **
-   [x] This pull request has a …
=> Bin-Sort in C

README.md, algorithms/ar-shsrt/python3/shell_sort.py
**Hi!**  
---
-   [ ] This pull request has …
=> implement shell sort in python3

README.md, algorithms/ar-binsrt/cpp/binsrt.cpp, algorithms/gr-dfsrh/python3/dfsrh.py
**Hi!**  
---
**Fixes #492 **
-   [&#10004; ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [&#10004; ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [&#10004; ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [&#10004; ] …
=> Depth First Search in Python3

README.md, algorithms/gr-dfsrh/c/depth_first_search.c
=> Added DFS Graph Algorithm in C

README.md, algorithms/gr-dfsrh/cpp/depth_first_search.cpp
=> Added DFS Graph Algorithm in C++

README.md, algorithms/ar-prfac/java/PrimeFactor.java, algorithms/gr-bfsrh/c/bfs.c
#505 
**Fixes #505 **
-   [x] I have mentioned the …
=> Added Prime factor algorithm in Java

README.md, algorithms/gr-bfsrh/csharp/BreadthFirst.cs, data-structures/ds-stk/java/Stack.java
**Hi!**  
---
-   [ ] This pull request has …
=> implement stack in java

README.md, algorithms/ar-prfac/python3/prime_factor.py, algorithms/gr-bfsrh/csharp/BreadthFirst.cs
**Fixes #545 [(Link)](https://github.com/FOSS-UCSC/FOSSALGO/issues/545)**
-   [x] This pull request shall only be merged once …
=> Added Prime Factors in Python 3

README.md, algorithms/gr-bfsrh/csharp/BreadthFirst.cs, algorithms/gr-dij/java/Dijkstra.java
**Hi!**  
**Fixes #533 *
-   [x] I have mentioned the …
=> Add Dijkstra's algorithm Java

README.md, algorithms/ar-isrt/javascript/insertion_sort.js
=> Added Insertion Sort in JavaScript

README.md, algorithms/ar-msrt/javascript/merge_sort.js, algorithms/gr-dij/java/Dijkstra.java
=> Added merge sort in Javascript

README.md, data-structures/ds-cque/c/circular_queue.c
=> Added Circular Queue In C

.all-contributorsrc, README.md, algorithms/ar-msrt/typescript/merge_sort.ts
=> Added merge sort in Typescript

README.md, algorithms/gr-dij/golang/dijkstras_algorithm.go
**Fixes #535 
-   [👍🏻  ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [👍🏻  ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [👍🏻  ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [👍🏻  ] This pull request has a descriptive title. 
-   [👍🏻  ] This pull request shall only be merged once the build passes.
-   [👍🏻  ] I have …
=> Added Dijkstra's Algorithm in GoLang

README.md, algorithms/ar-mexp/typescript/modular_exponential.ts
=> Adding modular exponential in Typescript

README.md, algorithms/ar-hsrt/java/HeapSort.java
**Hi!**  
---
**Fixes #540 **
-   [x] This pull request has a …
=> Added Heap Sort in Java and updated README.md about adding Heap Sort for Java

.all-contributorsrc, README.md, algorithms/ar-cochprb/java/CoinChange.java
Added the implementation of Coin Change problem in Java
**Hi!**  
---
**Fixes #570 **
-  &#9745; I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   &#9745;  I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   &#9745; My code follows the [skeleton code …
=> Added CoinChange.java

README.md, algorithms/ar-mexp/javascript/modular_exponential.js
=> Adding modular exponential in javascript

README.md, algorithms/ar-bsrt/csharp/BubbleSort.cs
**Hi!**  
---
**Fixes #485 **
-   [ x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [x ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [ x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [ x] This pull request has a …
=> Add bubble sort in charp to readme as well

README.md, algorithms/gr-dij/c/dijkstra_algorithm.c
**Hi!**  
---
**Fixes #531 **
-   [x] This pull request has a …
=> Added Dijkstra Algorithm [C]

algorithms/ar-msrt/java/MergeSort.java
This PR fixed for this issue https://github.com/FOSS-UCSC/FOSSALGO/issues/613#L46
=> Fixed Java Performance Issue  with System::arraycopy

README.md, algorithms/ar-expsq/typescript/exp_by_squaring.ts
=> Adding exponentiation by squaring in Typescript

README.md, algorithms/ar-lsrh/typescript/linear_search.ts
=> Adding linear search in Typescript

README.md, algorithms/ar-expsq/javascript/exponentiation_by_squaring.js
**Hi!**  
I have added exponentiation by squaring algorithm in javascript.
---
Fixes #617 
-   [x] This pull request shall …
=> Added exponetiation by squaring algorithm in javascript

README.md, data-structures/ds-pque/java/PriorityQueue.java
**Hi!**  
**Fixes ##556**
-   [ x ] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
-   [ x ] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
-   [ x ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).
-   [ x ] This pull request has a descriptive title. 
-   [ x ] This pull request shall only be merged once the build passes.
-   [ x ] I have …
=> Added Priority Queue #556

README.md, algorithms/gr-dij/python3/dijkstra.py
=> Added Dijkstra Algorithm in Python3

README.md, algorithms/ar-expsq/csharp/ExponentiationBySquaring.cs, algorithms/ar-expsq/typescript/exp_by_squaring.ts
=> Create C# implementation of Exponentiation using Squaring

README.md, algorithms/ar-expsq/python3/exponentiation_by_squaring.py
Exponentiation with squaring implemented in Python3, a/c to the guidelines. #603 #
=> Exponentiation with squaring implemented in Python3

README.md, algorithms/ar-expsq/c/exponentiation_by_squaring.c
**Hi!**  
Added exponentiation by squaring algorithm in C
---
**Fixes #598 **
-   [x] This pull request shall only be merged …
=> Added exponentiation by squaring algorithm in C

.all-contributorsrc, README.md, algorithms/ar-hsrt/csharp/HeapSort.cs
=> Implement heap sort in C#

README.md, algorithms/ar-slpsrt/c/ar_slpsrt.c
=> Sleep sort in C

README.md, data-structures/ds-cque/java/CircularQueue.java
=> Added Circular Queue in Java

README.md, data-structures/ds-stk/typescript/stack.ts
=> Added Stack in Typescript 

README.md, algorithms/ar-hsrt/typescript/heap_sort.ts
**Hi!**  
---
-   [ ] This pull request has …
=> Heap Sort Typescript Implementation

README.md, algorithms/ar-kmp/python3/knuth_morris_pratt.py, algorithms/ar-soer/java/SieveOfEratosthenes.java
=> Added Sieve of Eratosthenes Algorithm

README.md, data-structures/ds-que/typescript/queue.ts, data-structures/ds-stk/typescript/stack.ts
=> Added Queue in Typescript

README.md, algorithms/ar-lreg/python3/linear_regression.py
---
**Fixes [#741](https://github.com/FOSS-UCSC/FOSSALGO/issues/741)**
-   [x] This pull request shall only be merged once …
=> linear regression for python3

README.md, algorithms/ar-lscsa/golang/largest_sum_contiguous_subarray.go
=> Add Largest Sum Contiguous Subarray in Go

README.md, algorithms/ar-lreg/javascript/linear_regression.js
=> Added Linear Regression Javascript

README.md, algorithms/ar-lscsa/csharp/LargestSumContiguousSubArray.cs
**Fixes [#726](https://github.com/FOSS-UCSC/FOSSALGO/issues/726)** …
=> Add Largest Sum Contiguous Subarray in CSharp

README.md
Hi Guys! 👋  I've noticed you were lacking instructions on how to run TypeScript. I've took the liberty to do it myself, here is the PR! Let me know if you want me to open an Issue for this one. Cheers!
For example, `Added …
=> Added how to run Typescript

README.md, algorithms/ar-lscsa/typescript/largest_sum_contiguous_subarray.ts
=> Add Largest Sum Contiguous Subarray in TypeScript

README.md, algorithms/ar-lreg/c/linear_regression.c
=> Linear Regression in C

README.md, algorithms/gr-dfsrh/golang/dfsrh.go
=> Add Depth First Search in Golang

README.md, algorithms/ar-expsq/golang/exponentiation_by_square.go
=> Added Exponentiation by Squaring in Golang

README.md, algorithms/ar-lreg/typescript/linear_regression.ts
=> Added Linear Regression in Typescript

README.md, algorithms/ar-slpsrt/java/SleepSort.java
**Fixes https://github.com/FOSS-UCSC/FOSSALGO/issues/763**
-   [x] This pull request shall only be merged once the build …
=> Add Sleep Sort implementation for Java

README.md, algorithms/ar-shsrt/java/ShellSort.java
**Fixes https://github.com/FOSS-UCSC/FOSSALGO/issues/766**
-   [x] This pull request shall only be merged once the build …
=> Add Shell Sort implementation for Java

README.md, algorithms/ar-lscsa/java/LargestSumContiguousSubArray.java
=> Added Largest Sum Contiguous Subarray in Java

README.md, algorithms/ar-kmp/typescript/knuth_morris_pratt.ts
=> Added Knuth-Morris-Pratt in TypeScript

README.md, algorithms/ar-kmp/javascript/knuth_morris_pratt.js
=> Added Knuth-Morris-Pratt in Javascript

README.md, algorithms/ar-binsrt/typescript/bin_sort.ts
=> Added Bin Sort in Typescript

README.md, algorithms/ar-lscsa/cpp/largest_sum_contiguous_subarray.cpp
**Fixes #724 }**
-   [ ] This pull request has a descriptive title. 
-   [ ] This pull request shall only be merged once the build passes.
-   [ ] I have mentioned the issue …
=> Added largest sum contiguous subarray code in C++

README.md, algorithms/gr-dfsrh/javascript/dfs.js
**Fixes [#494](https://github.com/FOSS-UCSC/FOSSALGO/issues/494)** …
=> Added Depth First Search in Javascript

README.md, algorithms/ar-lsrh/golang/linear_search.go
**Fixes  https://github.com/FOSS-UCSC/FOSSALGO/issues/775**
-   [x] This pull request shall only be merged once the build …
=> Added linear search [Go]

README.md, algorithms/gr-dfsrh/java/DepthFirstSearch.java
**Fixes [#490](https://github.com/FOSS-UCSC/FOSSALGO/issues/490)** …
=> Added Depth First Search in Java

README.md, algorithms/ar-kmp/python3/knuth_morris_pratt.py, algorithms/ar-lreg/cpp/linear_regression.cpp
**Hi!**  
---
-   [ ] This pull request has …
=> Linear Regression in C++. #733

README.md, algorithms/gr-bfsrh/java/BreadthFirstSearch.java
**Fixes [#801](https://github.com/FOSS-UCSC/FOSSALGO/issues/801)** …
=> Added Breadth First Search in Java

README.md, algorithms/ar-msrt/cpp/merge_sort.cpp
=> Mergesortcpp

README.md, algorithms/ar-cochprb/csharp/CoinChangeProblem.cs
=> Added Coin Change Problem in C#

README.md, algorithms/ar-isrt/cpp/insertion_sort.cpp, algorithms/ar-msrt/cpp/merge_sort.cpp
=> Insertionsort in c++

algorithms/ar-cochprb/cpp/coinchange.cpp
Coin change, standard problem solved using dynamic programming.
-   [x] This pull request shall …
=> coinchange.cpp

algorithms/ar-rcprb/cpp/rodcutting.cpp
Rod cutting problem, a standard problem is solved using dynamic programming.
-   [x] This pull request shall only be merged …
=> rodcutting.cpp

algorithms/ar-lcs/cpp/longestcommonsubsequence.cpp
longest common subsequence, or LCS, is a standard problem and can be done in O(nm) time using dynamic programming.
-   [x] …
=> longestcommonsubsequence.cpp

data-structures/ds-dlinklst/cpp/doublelinkedlist.cpp
I am implementing a doubly linked list.
I will take the information of the faculty member as input.
-   [x] This pull request …
=> doublelinkedlist.cpp
